export const LOAD_ALL = "LOAD_ALL";
export const LOAD_ALL_SUCCESS = "LOAD_ALL_SUCCESS";
export const LOAD_ALL_ERROR = "LOAD_ALL_ERROR";

export const SEND_MESSAGE = "SEND_MESSAGE";
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";
export const SEND_MESSAGE_ERROR = "SEND_MESSAGE_ERROR";
